---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zeref/public_html/
    - /bin/mkdir -p $DEPLOYPATH/public
    - /bin/cp -r public/. $DEPLOYPATH/public/
    - /bin/cp server.js package.json $DEPLOYPATH
    - export NODE_ENV=production
    - source /home/zeref/nodevenv/GuardYourData/20/bin/activate && cd $DEPLOYPATH && npm install --production
    - pkill -f "node server.js" || true
    - nohup node server.js > output.log 2>&1 &
