services:
  - type: web
    name: fin7900-training
    env: node
    region: oregon
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
